#!/usr/bin/env python3
"""Moves inline style="" attributes out of the pages, so the Content-Security-Policy
can drop 'unsafe-inline' from style-src.

Every distinct style attribute becomes one class, .is-<8 hex of its declarations>,
written to assets/releaseshow-inline.css and linked right after the main stylesheet. Each
declaration is emitted with !important, which keeps the precedence an inline style
had over the stylesheet (an inline declaration beats every normal one).

Run it after editing a page:   python3 tools/csp-inline-styles.py
It rewrites the pages in place and regenerates the CSS from all of them, so it is
idempotent. tools/build-dist.sh runs it with --check and refuses to build while
any page still carries a style attribute.
"""
import hashlib, html, pathlib, re, sys

PAGES = ['index.html', '404.html']
CSS = pathlib.Path('assets/releaseshow-inline.css')
MAIN = '<link rel="stylesheet" href="/assets/releaseshow.css">'
LINK = '<link rel="stylesheet" href="/assets/releaseshow-inline.css">'
STYLE_ATTR = re.compile(r'\sstyle="([^"]*)"')
HEADER = '/* Generated by tools/csp-inline-styles.py from the pages\' former style="" attributes. Do not edit. */\n'


def declarations(value):
    """Splits a style attribute on top-level semicolons (not inside url() or quotes)."""
    out, cur, depth, quote = [], '', 0, None
    for ch in value:
        if quote:
            cur += ch
            if ch == quote:
                quote = None
            continue
        if ch in '"\'':
            quote = ch
        elif ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        elif ch == ';' and depth == 0:
            out.append(cur.strip()); cur = ''
            continue
        cur += ch
    out.append(cur.strip())
    return [d for d in out if d]


def rule_body(value):
    decls = []
    for d in declarations(html.unescape(value)):
        decls.append(d)
    return ';'.join(decls)


def class_for(body):
    return 'is-' + hashlib.sha256(body.encode()).hexdigest()[:8]


def rewrite(text, rules):
    def tag(m):
        t = m.group(0)
        sm = STYLE_ATTR.search(t)
        if not sm:
            return t
        body = rule_body(sm.group(1))
        cls = class_for(body)
        rules[cls] = body
        t = t[:sm.start()] + t[sm.end():]
        cm = re.search(r'\sclass="([^"]*)"', t)
        if cm:
            names = cm.group(1).split()
            if cls not in names:
                names.append(cls)
            t = t[:cm.start()] + f' class="{" ".join(names)}"' + t[cm.end():]
        else:
            name_end = re.match(r'<[A-Za-z][\w:-]*', t).end()
            t = t[:name_end] + f' class="{cls}"' + t[name_end:]
        return t
    return re.sub(r'<[A-Za-z][\w:-]*\b[^>]*\sstyle="[^"]*"[^>]*>', tag, text)


def existing_rules(text):
    """Rules for classes the pages already carry (from an earlier run)."""
    if not CSS.exists():
        return {}
    known = dict(re.findall(r'^:is\(\.(is-[0-9a-f]{8}), #_#_#_\)\{(.*)\}$', CSS.read_text(), re.M))
    used = set(re.findall(r'\b(is-[0-9a-f]{8})\b', text))
    return {k: v for k, v in known.items() if k in used}


def main():
    check = '--check' in sys.argv
    bad = [p for p in PAGES if STYLE_ATTR.search(re.sub(r'<script.*?</script>', '', pathlib.Path(p).read_text(), flags=re.S))]
    if check:
        missing = [p for p in PAGES if 'is-' in pathlib.Path(p).read_text() and LINK not in pathlib.Path(p).read_text()]
        if bad or missing:
            for p in bad:
                print(f'{p} still has a style="" attribute: run python3 tools/csp-inline-styles.py', file=sys.stderr)
            for p in missing:
                print(f'{p} uses is-* classes but does not link {CSS}', file=sys.stderr)
            sys.exit(1)
        return
    rules = {}
    for p in PAGES:
        path = pathlib.Path(p)
        text = path.read_text(encoding='utf-8')
        rules.update(existing_rules(text))
        text = rewrite(text, rules)
        if re.search(r'\bis-[0-9a-f]{8}\b', text) and LINK not in text:
            assert MAIN in text, f'{p}: main stylesheet link not found'
            text = text.replace(MAIN, MAIN + '\n' + LINK, 1)
        path.write_text(text, encoding='utf-8')
    CSS.write_text(HEADER + ''.join(f':is(.{k}, #_#_#_){{{v}}}\n' for k, v in sorted(rules.items())), encoding='utf-8')
    print(f'{CSS}: {len(rules)} rules from {", ".join(PAGES)}')


if __name__ == '__main__':
    main()
